### ISSUE TITLE
[question]how to avoid tls in tls characteristics in your implementation?

### ISSUE THREAD

**Issue by FranzKafkaYu** [chengchenwish/overplus#10]
hello developer,do you have any plan to solve tls in tls characteristics in Trojan protocol?and is there any method to achieve this?it would be a great enhancement if you can make it.

**Comment by xyanrch** [comment]
currently, tls in tls characteristics still exist in my implementation. It is still unclear how GFW detects Trojan protocol, so any implementation is still a try.  But your question is a good suggestion, I will consider it in future.

**Comment by linusdrop** [comment]
Он используется уже некоторое время, и gfw пока не может блокировать Overplus.
