### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by WikiHacker** [chengchenwish/overplus#11]
Nov 10 05:53:25 OverPlus systemd[1]: Started overplus - An proxy tool helps you bypass GFW.
Nov 10 05:53:25 OverPlus overplus[14365]: [2022-11-10 05:53:25][NOTICE] /__w/1/s/Server/main.cpp main: line: 35 [140091>
Nov 10 05:53:25 OverPlus systemd[1]: overplus.service: Deactivated successfully.

Ubuntu 22.10

**Comment by xyanrch** [comment]
有更多的log吗, 或者重新start一下，sudo service overplus start

**Comment by WikiHacker** [comment]
after restart the system looks better. thanks

Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:

if anyone skip this, or not completed, that will create problem. re-try and will work fine.
