### ISSUE TITLE
协议的SNI

### ISSUE THREAD

**Issue by fengguowudi** [chengchenwish/overplus#17]
搭建完成后并未返回SNI域名

**Comment by xyanrch** [comment]
请详细说明，是server端没返回还是client端没返回，期待的效果是啥？

**Comment by fengguowudi** [comment]
该项目搭建成功之后，我要是想用Xray内核连接，请问SNI应该填写什么，是否需要跳过证书验证？

**Comment by xyanrch** [comment]
如果是自签名证书的话，直接跳过验证。如果是申请的证书的话，填证书的名字就可以了
