### ISSUE TITLE
core dumped in new release

### ISSUE THREAD

**Issue by mk990** [chengchenwish/overplus#19]
./overplus -h 
terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::json_parser::json_parser_error>'
  what():  -h: cannot open file
[1]    1150364 IOT instruction (core dumped)  ./overplus -h

**Comment by xyanrch** [comment]
In version v1.0.4 overplus doesn't support '-h' argument, only supported command is: "./overplus server.json" , ,server.json is your config file path.

I have supported '-h' argument in latest code but didn't release it, you can clone the code and compile it by yourself.
