### ISSUE TITLE
shadowrocket不能识别

### ISSUE THREAD

**Issue by ghost** [chengchenwish/overplus#8]
windows v2rayN 可以通过trojan 使用，但是ios shadowrocket 正常trojan 链接不能连接，请问在shaodwrocket 上有什么必要开启的配置呢？

**Comment by xyanrch** [comment]
是不是开启了多路复用，关掉多路复用试一下。
我就用的shadowsocks，可以的

**Comment by ghost** [comment]
Ok了，可以

**Comment by ghost** [comment]
感谢
