### ISSUE TITLE
抗封锁能力

### ISSUE THREAD

**Issue by ghost** [chengchenwish/overplus#9]
系统-ubuntu20
安装脚本- VERSION="v1.0.2"

只跑了一个晚上流量就出现端口封锁
同机hysteria naiveproxy 端口依然存活
![image](https://user-images.githubusercontent.com/114660387/199383896-8ac84ab4-3160-4bf2-8687-fe4fe730e93b.png)
![image](https://user-images.githubusercontent.com/114660387/199383932-d326baff-b6c2-48c1-88ca-a26e7c92f6d7.png)

**Comment by xyanrch** [comment]
不清楚怎么测的，用的哪个端口，哪个客户端

**Comment by ghost** [comment]
客户端是v2rayN
服务端端口是2024
然后站长工具的端口检测结果是关闭,使用国外端口扫描结果就是开启，推测是端口封锁了，2024端口只用来使用overplus服务

**Comment by flowflic** [comment]
后面换端口还封吗
